# Generated by Django 5.2.6 on 2025-09-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='giphy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('title', models.TextField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='meme',
            name='user',
        ),
    ]
