# Generated by Django 5.2.6 on 2025-09-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_store', '0002_giphy_remove_meme_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='giphy',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meme',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
