# Generated by Django 5.2.6 on 2025-09-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_store', '0003_giphy_likes_meme_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
